version: '3.8'

services:
  db:
    image: postgres:15
    container_name: comissions_db
    restart: always
    environment:
      POSTGRES_DB: comissions
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    image: eduardofelichak/comissions-backend
    container_name: comissions_backend
    restart: always
    ports:
      - "3333:3333"
    depends_on:
      - db

  frontend:
    image: eduardofelichak/comissions-frontend
    container_name: comissions_frontend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - backend

volumes:
  pgdata: