services:
  db:
    image: postgres:15
    container_name: comissions_db
    restart: always
    environment:
      POSTGRES_DB: comissions
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: comissions_backend
    restart: always
    ports:
      - "3333:3333"
    depends_on:
      - db
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    command: npm run dev

volumes:
  pgdata:
